-- MySQL Script generated by MySQL Workbench
-- Fri Nov 17 09:57:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sound
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sound
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sound` DEFAULT CHARACTER SET utf8 ;
USE `sound` ;

-- -----------------------------------------------------
-- Table `sound`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound`.`Autor` (
  `id_autor` INT NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `nome_original` VARCHAR(45) NULL,
  `nome_artistico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound`.`Categoria` (
  `id_categoria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound`.`Playlist` (
  `id_playlist` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `data_criacao` DATE NULL,
  `fk_categoria` INT NOT NULL,
  PRIMARY KEY (`id_playlist`),
  INDEX `playlist_categoria_idx` (`fk_categoria` ASC) VISIBLE,
  CONSTRAINT `playlist_categoria`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `sound`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound`.`Musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound`.`Musica` (
  `id_musica` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `letra` LONGTEXT NULL,
  `data_lancamento` DATE NULL,
  `duracao` CHAR(5) NULL,
  `fk_categoria` INT NOT NULL,
  PRIMARY KEY (`id_musica`),
  INDEX `musica_categoria_idx` (`fk_categoria` ASC) VISIBLE,
  CONSTRAINT `musica_categoria`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `sound`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound`.`Musica_Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound`.`Musica_Playlist` (
  `fk_musica` INT NOT NULL,
  `fk_playlist` INT NOT NULL,
  PRIMARY KEY (`fk_musica`, `fk_playlist`),
  INDEX `playlist_idx` (`fk_playlist` ASC) VISIBLE,
  CONSTRAINT `musica`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `sound`.`Musica` (`id_musica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `playlist`
    FOREIGN KEY (`fk_playlist`)
    REFERENCES `sound`.`Playlist` (`id_playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound`.`Musica_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound`.`Musica_Autor` (
  `fk_musica` INT NOT NULL,
  `fk_autor` INT NOT NULL,
  PRIMARY KEY (`fk_musica`, `fk_autor`),
  INDEX `autor_idx` (`fk_autor` ASC) VISIBLE,
  CONSTRAINT `musica2`
    FOREIGN KEY (`fk_musica`)
    REFERENCES `sound`.`Musica` (`id_musica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `autor`
    FOREIGN KEY (`fk_autor`)
    REFERENCES `sound`.`Autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
